version: '2.4'

services:

  mongo-todo:
    image : mongo:4.2.3
    volumes:
      - ./data/mongodb_data:/data/db
    ports:
      - 27017:27017

  todo-server:
    build: todo-server
    command: npm start
    ports:
      - 4000:4000
    environment: 
      - MONGO_HOST=mongo-todo
      - MONGO_PORT=27017
      - MONGO_DATABASE=test
      - GRAPHIQL=false

  todo-client:
    build:
      context: todo-client
      args:
        - VUE_APP_GRAPQL_URL=http://localhost:4000/graphql
    ports:
      - 8080:80
